textproc/hunspell: always link against C++11 library
C++11 isn't ABI-compatible with C++98 on GCC platforms, so build the
port using lang/gcc which since r449590 defaults to C++14. This should
fix C++11 consumers like www/firefox.

../../extensions/spellcheck/hunspell/glue/Unified_cpp_hunspell_glue0.o: In function `mozHunspell::SetDictionary(char16_t const*)':
Unified_cpp_hunspell_glue0.cpp:(.text._ZN11mozHunspell13SetDictionaryEPKDs+0x4a4): undefined reference to `Hunspell::get_dict_encoding[abi:cxx11]() const'
../../extensions/spellcheck/hunspell/glue/Unified_cpp_hunspell_glue0.o: In function `mozHunspell::Check(char16_t const*, bool*)':
Unified_cpp_hunspell_glue0.cpp:(.text._ZN11mozHunspell5CheckEPKDsPb+0x148): undefined reference to `Hunspell::spell(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
../../extensions/spellcheck/hunspell/glue/Unified_cpp_hunspell_glue0.o: In function `mozHunspell::Suggest(char16_t const*, char16_t***, unsigned int*)':
Unified_cpp_hunspell_glue0.cpp:(.text._ZN11mozHunspell7SuggestEPKDsPPPDsPj+0x16c): undefined reference to `Hunspell::suggest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'

Submitted by:	jhibbits (based on)
Differential Revision:	https://reviews.freebsd.org/D12515