devel/icu-le-hb: switch to C++11, required by ICU >= 59
In file included from LayoutEngine.cpp:8:
In file included from ./LETypes.h:14:
In file included from /usr/local/include/unicode/utypes.h:38:
/usr/local/include/unicode/umachine.h:347:13: error: unknown type name 'char16_t'
    typedef char16_t UChar;
            ^

PR:		218788